HillDwarf.test
PavelHuman/dnd-character-generator pull request #43
Opened 2022-03-28 20:41 UTC by PavelHuman

2022-03-28 20:59 UTC, dandgerson requested changes

2022-03-28 20:59 UTC, dandgerson commented on src/tests/HillDwarf.test.js
> +  })
можно добавить тест-кейсы про то, что hillDwarf должен быть инстансом Dwarf и Race

2022-03-28 20:59 UTC, dandgerson commented on src/tests/HillDwarf.test.js
> +}
эта функция уже была объявлена, давай переиспользуем её.
Предлагаю создать файл utils.js и положить фукнцию туда. И заимпортить её из этого файла во все места где она может пригодиться)

2022-03-28 20:59 UTC, dandgerson commented on src/tests/HillDwarf.test.js
> +  })
похоже это тест кейсы для Race. Для Race они уже прописаны и Race выполняет эти требования.

Если HillDwarf будет наследовать Race, то отнаследует и выполнение всех тест-кейсов. Ещё раз тестировать на эти требования избыточно. Достаточно будет удостовериться, что HillDwarf наследует от Race

2022-03-28 20:59 UTC, dandgerson commented on src/index.js
>  console.log(dwarf)
кажется, что можно удалить ненужные логи. чтобы не отвлекали лишним выводом

2022-03-28 20:59 UTC, dandgerson commented on src/tests/HillDwarf.test.js
> +  describe('increaseAbilityScore', () => {
этот. тест-кейс мы тоже уже предъявили Race и Race его выполняет) Он тут избыточен.

2022-03-28 21:07 UTC, dandgerson commented
Давай добавим тест кейсы про то что:
1. `hillDwarf` должен быть инстансом `Dwarf`
2. `hillDwarf` должен быть инстансом `Race`
3. `hillDwarf` должен иметь свойство `Dwarfven Toughness`
4. `dwarvenToughness` должна иметь тип трейта `effect`
5. `dwarvenToughness` должна повышать `hitPointMaximumIncrease` на 1. И повышать `hitPointMaximumIncrease` на 1 при каждом повышении уровня
6. `hillDwarf.abilityScoreIncrease` при инициализации в конструкторе должно повышаться свойство wisdom со значением 1

2022-03-28 21:13 UTC, dandgerson commented
старайся придерживаться принципа TDD:
1. написал тест кейс. Запустил тесты - тесты валятся (красное)
2. Пофиксил, чтобы было зелёное (когда нет красного =)),
3. улучшаешь код, чтобы было красиво и возвращайся к пункту `1`

2022-03-29 07:22 UTC, PavelHuman commented
Дружище, буду стараться

2022-03-30 20:28 UTC, dandgerson approved these changes

2022-03-30 20:28 UTC, merged